---
title: "Importing and Managing Financial Data in R"
output: html_notebook
---

```{r setup}
library(quantmod)
```

```{r}
# Load the quantmod package
library(quantmod)

# Assign SPY data to 'spy' using auto.assign argument
spy <- getSymbols("SPY", auto.assign = FALSE)

# Look at the structure of the 'spy' object
str(spy)

# Assign JNJ data to 'jnj' using env argument
jnj <- getSymbols("JNJ", env = NULL)

# Look at the structure of the 'jnj' object
str(jnj)
```


```{r}
# Load the Quandl package
library(Quandl)

# Import GDP data from FRED
gdp <- Quandl("FRED/GDP")

# Look at the structure of the object returned by Quandl
str(gdp)
```

```{r}
# Import GDP data from FRED as xts
gdp_xts <- Quandl("FRED/GDP", type="xts")

# Look at the structure of gdp_xts
str(gdp_xts)


# Import GDP data from FRED as zoo
gdp_zoo <- Quandl("FRED/GDP", type="zoo")


# Look at the structure of gdp_zoo
str(gdp_zoo)
```

```{r}
# Create an object containing the Pfizer ticker symbol
symbol <- "PFE"


# Use getSymbols to import the data
getSymbols("PFE", auto.assign = TRUE)


# Look at the first few rows of data
head(PFE)
```

A list of all currencies is provided in the quantmod package

```{r}
quantmod::oanda.currencies
```

```{r}
# Create a currency_pair object
currency_pair <- "GBP/CAD"

# Load British Pound to Canadian Dollar exchange rate data
getSymbols(currency_pair, src = "oanda")


# Examine object using str()
str(GBPCAD)

# Try to load data from 190 days ago
getSymbols(currency_pair, from = Sys.Date() - 190, to = Sys.Date(), src = "oanda")
```

```{r}
# Create a series_name object
series_name <- "UNRATE"

# Load the data using getSymbols
getSymbols(series_name, src = "FRED")

# Create a quandl_code object
quandl_code <- paste0("FRED/", series_name)

# Load the data using Quandl
unemploy_rate <- Quandl(quandl_code)
```


# Extracting and transforming data

```{r}
load(here::here("data/importing_financial_data/DC.RData"))
```

```{r}
# Extract the close column
dc_close <- Cl(DC)

# Look at the head of dc_close
head(dc_close)

# Extract the volume column
dc_volume <- Vo(DC)

# Look at the head of dc_volume
head(dc_volume)
```
```{r}
# Extract the high, low, and close columns
dc_hlc <- HLC(DC)

# Look at the head of dc_hlc
head(dc_hlc)

# Extract the open, high, low, close, and volume columns
dc_ohlcv <- OHLCV(DC)


# Look at the head of dc_ohlcv
head(dc_ohlcv)
```


```{r}
# Download CME data for CL and BZ as an xts object
oil_data <- Quandl(code = c("CME/CLH2016", "CME/BZH2016"), type = "xts")

# Look at the column names of the oil_data object
colnames(oil_data)

# Extract the Open price for CLH2016
cl_open <- getPrice(oil_data, symbol = "CLH2016", prefer = "Open$")

# Look at January, 2016 using xts' ISO-8601 subsetting
cl_open["2016-01"]
```

